---
## SELinuxのモード変更
- name: configure / Selinux permissived
  selinux:
    policy: targeted
    state: permissive
  #when : ansible_selinux.config_mode == 'enforcing'

## IPv6 インターフェースの無効化
- name: configure / Desable ipv6 interface
  sysctl:
    state: present
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

## yum update
- name: configure / Update yum package
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: configure / Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: install / firewalld
  yum:
    name: firewalld
    state: latest

- name: start / firewalld
  service:
    name: firewalld
    state: started